---
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '!v[0-9]+.0.0'
name: post-release
jobs:
  main:
    name: update major version pointer
    runs-on: ubuntu-latest
    steps:
      - name: Get version prefix
        id: version-prefix
        run: |
          GIT_REF=${{ github.ref }}
          echo "::set-output name=main::${GIT_REF:10:2}"

      - name: Checkout major version branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.version-prefix.outputs.main }}

      - name: Fast-forward branch to newest version
        run: |
          git merge --ff-only --no-edit ${{ github.ref }}
          git push
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
