---
on:
  push:
    tags:
      - v[0-9]+.0.0
name: post-major-release
jobs:
  main:
    name: create major version pointer
    runs-on: ubuntu-latest
    steps:
      - name: Get version prefix
        id: version-prefix
        run: |
          GIT_REF=${{ github.ref }}
          echo "::set-output name=main::${GIT_REF:10:2}"

      - name: Checkout new release
        uses: actions/checkout@v3

      - name: Create branch for pointer
        run: |
          git branch $VERSION_PREFIX
          git push --set-upstream origin ${{ steps.version-prefix.outputs.main }}
        env:
          GIT_AUTHOR_NAME: ${{ github.actor }}
          GIT_AUTHOR_EMAIL: ${{ github.actor }}@users.noreply.github.com
          GIT_COMMITTER_NAME: ${{ github.actor }}
          GIT_COMMITTER_EMAIL: ${{ github.actor }}@users.noreply.github.com
